
package frames;

import clases.Actor;
import clases.Clasificacion;
import clases.ControladorActor;
import clases.ControladorClasificacion;
import clases.ControladorDirector;
import clases.ControladorGenero;
import clases.Pelicula;
import clases.ControladorPelicula;
import clases.ControladorPeliculaActor;
import clases.ControladorPeliculaClasificacion;
import clases.ControladorPeliculaDirector;
import clases.ControladorPeliculaGenero;
import clases.Director;
import clases.ErrorPelicula;
import clases.Genero;
import clases.MyTableModel;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class frmActor extends javax.swing.JFrame {

    private DefaultTableModel modeloPeliculas;
    MyTableModel modeloActores;
    MyTableModel modeloDirectores;
    MyTableModel modeloGeneros;
    DefaultComboBoxModel modeloClasificacion;
    
    /**
     * Creates new form frmAsignatura
     */
    public frmActor() {
        initComponents();
        jFrame1.setSize(1000, 600);
        this.setLocationRelativeTo(null);
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        rellenoTabla();
    }
    
    
    //---------------------creacion de tabla--------------------------------
    public void rellenoTabla(){
        String[] encabezadosTabla={"Código","Actor"};
        modeloPeliculas=new DefaultTableModel();
        ArrayList<Actor> asignaturas = new ArrayList();
        Object[] fila = new Object[5];
        
        try {
            asignaturas = ControladorActor.Buscar();
            modeloPeliculas.setColumnIdentifiers(encabezadosTabla);
            Iterator<Actor> peli = asignaturas.iterator();
        
            while (peli.hasNext()) {
                    
                    fila[0] = peli.next();
                    fila[1] = peli.next();
//                    fila[2] = peli.next();
//                    fila[3] = peli.next();
//                    fila[4] = peli.next();
                    
                    
                    modeloPeliculas.addRow(fila);
                    tblPelicula.setModel(modeloPeliculas);
                }
            
        } catch (ErrorPelicula ex) {
            Logger.getLogger(frmActor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     }   
    
   public void limpiar(){
       txtActor.setText("");
       txtCodigoActor.setText("");
   }
   
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoActor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtActor = new javax.swing.JTextField();
        lblAgregar1 = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEliminar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPelicula = new javax.swing.JTable();
        lblAgregar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Código:");
        jFrame1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        txtCodigoActor.setEnabled(false);
        jFrame1.getContentPane().add(txtCodigoActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 180, -1));

        jLabel1.setText("Actor:");
        jFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        jFrame1.getContentPane().add(txtActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 180, -1));

        lblAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        lblAgregar1.setText("Modificar");
        lblAgregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregar1MouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(lblAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        lblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        lblCancelar.setText("Cancelar");
        lblCancelar.setMinimumSize(new java.awt.Dimension(600, 600));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel11.setText("MODIFICAR");
        jFrame1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar.png"))); // NOI18N
        lblModificar.setText("modificar");
        lblModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMouseClicked(evt);
            }
        });
        getContentPane().add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));

        jLabel4.setText("ACTORES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        lblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/delete.png"))); // NOI18N
        lblEliminar.setText("eliminar");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, -1, -1));

        tblPelicula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Actor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPelicula);
        if (tblPelicula.getColumnModel().getColumnCount() > 0) {
            tblPelicula.getColumnModel().getColumn(0).setResizable(false);
            tblPelicula.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 700, 90));

        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/add.png"))); // NOI18N
        lblAgregar.setText("agregar");
        lblAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
        });
        getContentPane().add(lblAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/back.png"))); // NOI18N
        jLabel2.setText("Regresar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarMouseClicked
        Actor peli=new Actor();
        if(tblPelicula.getSelectedRow()!=-1){
            try {
                int seleccion;
                seleccion = tblPelicula.getSelectedRow();
                peli.setIdActor(tblPelicula.getValueAt(seleccion, 0).toString());
                ControladorActor.Eliminar(peli);
                JOptionPane.showMessageDialog(null, "La eliminacion fue correcta");
               modeloPeliculas.removeRow(tblPelicula.getSelectedRow());
            } catch (ErrorPelicula ex) {
                JOptionPane.showMessageDialog(null, "Elija una fila de la tabla");
            }
        }
    }//GEN-LAST:event_lblEliminarMouseClicked

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        frmActorAgregar add=new frmActorAgregar();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAgregarMouseClicked

    private void lblModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMouseClicked
         if(tblPelicula.getSelectedRow()!=-1){
            int seleccion; 
            jFrame1.setVisible(true);
            this.setVisible(false);
            
            seleccion = tblPelicula.getSelectedRow();
            txtCodigoActor.setText(tblPelicula.getValueAt(seleccion, 0).toString());
            txtActor.setText((tblPelicula.getValueAt(seleccion, 1).toString()));
            txtCodigoActor.requestFocus();

        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila de la tabla");
        }
    }//GEN-LAST:event_lblModificarMouseClicked

    private void lblAgregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregar1MouseClicked
        String id=txtCodigoActor.getText();
        String pelicula=txtActor.getText();
        System.out.println(id);

        if (id.isEmpty() && pelicula.isEmpty()) {
            JOptionPane.showMessageDialog(null, "rellene todos los campos por favor");
        }else{
                try{
                    Actor actor=new Actor();
                    actor.setIdActor(id);
                    actor.setActor(pelicula);
                    ControladorActor.Modificar(actor);
                    System.out.println("Todo se ejecuto con exito");
                } catch (ErrorPelicula ex) {
                    Logger.getLogger(frmPeliculaModificar.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        
    }//GEN-LAST:event_lblAgregar1MouseClicked

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        jFrame1.setVisible(false);
        this.setVisible(true);
        rellenoTabla();
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        frmMenu menu=new frmMenu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmActor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmActor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmActor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmActor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmActor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblAgregar1;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JTable tblPelicula;
    public javax.swing.JTextField txtActor;
    public javax.swing.JTextField txtCodigoActor;
    // End of variables declaration//GEN-END:variables
}
