/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

/**
 *
 * @author Enrique
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDirectores = new javax.swing.JButton();
        btnClasificacion = new javax.swing.JButton();
        btnActores = new javax.swing.JButton();
        btnGenero = new javax.swing.JButton();
        btnCartelera = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDirectores.setText("Directores");
        btnDirectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnDirectores, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        btnClasificacion.setText("Clasificacion");
        btnClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasificacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        btnActores.setText("Actores");
        btnActores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnActores, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        btnGenero.setText("Genero");
        btnGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        btnCartelera.setText("Cartelera");
        btnCartelera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarteleraActionPerformed(evt);
            }
        });
        getContentPane().add(btnCartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarteleraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarteleraActionPerformed
       frmPeliculas peli=new frmPeliculas();
       peli.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnCarteleraActionPerformed

    private void btnDirectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectoresActionPerformed
       frmDirector peli=new frmDirector();
       peli.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnDirectoresActionPerformed

    private void btnActoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActoresActionPerformed
        frmActor peli=new frmActor();
       peli.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnActoresActionPerformed

    private void btnClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasificacionActionPerformed
        frmClasificacion peli=new frmClasificacion();
       peli.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnClasificacionActionPerformed

    private void btnGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneroActionPerformed
        frmGenero peli=new frmGenero();
       peli.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActores;
    private javax.swing.JButton btnCartelera;
    private javax.swing.JButton btnClasificacion;
    private javax.swing.JButton btnDirectores;
    private javax.swing.JButton btnGenero;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
